services:
  - type: web
    name: hydra-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        value: "-4827638107"
      - key: PYTHON_VERSION
        value: "3.11" 